on : 
  push :
    branches :
      - "main"
      - "release/*"
  pull_request :
    branches :
      - "main"
jobs :
  job1 : 
    runs-on : ubuntu-latest
    steps :
     - name : check repo
       uses : actions/checkout@v3
     - name: print greeting
       run: echo Hello world!!
  job2 :
    runs-on : ubuntu-latest
    needs : job1
    steps :
      - name : check repo
        run : actions/checkout@v3
      - name : check nslookup od domain
        run : nslookup dbpki.db.com
      
 
      
      
    
    
