on : 
  push :
    branches :
      - "main"
      - "release/*"
  pull_request :
    branches :
      - "main"
jobs :
  job1 : 
    runs-on : ubuntu-latest
    steps :
     - name : check repo
       uses : actions/checkout@v3
     - name: print greeting
       run: echo Hello world!!
 
      
      
    
    
